
version: 2.1

orbs:
  docker: circleci/docker@1.4.0

jobs:

  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run Check Script
          command: ./check.sh

  do-tag:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    resource_class: small
    steps:
      - checkout
      
      - add_ssh_keys:
          fingerprints:
            - "66:e2:76:a8:ca:51:54:d9:1d:11:30:dc:e5:b1:7f:0d"
              
      - run:
          name: Run Check Script
          command: |
            git tag "build-$CIRCLE_BUILD_NUM"
            git push --tags

workflows:
  workflow:
    jobs:
      - build

      - tag-approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - main

      - do-tag:
          requires:
            - tag-approval

