
version: 2.1

orbs:
  docker: circleci/docker@1.4.0

commands:
  do-check:
    steps:
      - run:
          name: Run Check Script
          command: check.sh

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    steps:
      - checkout
      - do-check
      
workflows:
  welcome:
    jobs:
      - build

