
version: 2.1

orbs:
  docker: circleci/docker@1.4.0
  github-cli: circleci/github-cli@1.0.2

jobs:

  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run Build Script
          command: ./build.sh

  do-tag:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    resource_class: small
    steps:
      - checkout

      - run:
          name: Run Build Script
          command: ./build.sh

      - add_ssh_keys:
          fingerprints:
            - "66:e2:76:a8:ca:51:54:d9:1d:11:30:dc:e5:b1:7f:0d"

      # - run:
      #     name: Run Release Script
      #     command: |
      #       git config user.email "no-reply@github.com"
      #       git config user.name "Release Script"

      - run:
          name: Run Release Script
          command: ./release.sh

      - run:
          name: Dump env
          command: env


workflows:
  workflow:
    jobs:
      - build

      - tag-approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - main

      - do-tag:
          requires:
            - tag-approval

