
version: 2.1

orbs:
  docker: circleci/docker@1.4.0

# commands:
#   do-check:
#     steps:
#       - run:
#           name: Run Check Script
#           command: ./check.sh

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run Check Script
          command: ./check.sh

  do-tag:
    steps:
      - checkout
      - run:
          name: Run Check Script
          command: |
            git tag "job-$CIRCLE_BUILD_NUM"
            git push --tags

workflows:
  workflow:
    jobs:
      - build:
        jobs:
          - build

      - tag-approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - main

      - do-tag:
          requires:
            - tag-approval
          jobs:
            - do-tag
