
version: 2.1

# Use a package of configuration called an orb.
orbs:
  welcome: circleci/welcome-orb@0.4.1
  docker: circleci/docker@1.4.0

# commands:
#   add-ssh:
#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - "26:7a:89:de:da:d1:dd:ad:73:b2:97:0c:6f:03:bf:a0"

#   setup-build:
#     steps:
#       - add-ssh
#       - checkout

jobs:
  build:
    # environment:
    #   JVM_OPTS: -Xmx3200m
    #   TERM: dumb
    docker:
      - image: circleci/openjdk:11.0.9.1-jdk-buster
    steps:
      - checkout

workflows:
  welcome:
    jobs:
      - build

