
version: 2.1

orbs:
  docker: circleci/docker@1.4.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    steps:
      - checkout

workflows:
  welcome:
    jobs:
      - build

